### ISSUE TITLE
Question about OpenStreetMap hashes / Reference IDs and a meta question about questions

### ISSUE THREAD

**Issue by rossbernet** [sharedstreets/curblr#18]
Hey @emilyeros and/or other CurbLR fans,

I am reading this: 

https://medium.com/sharedstreets/how-the-sharedstreets-referencing-system-works-2097b0d61b52

And I read this sentence, 

> SharedStreets generates a global set of street reference IDs, using geometries from OpenStreetMap.

and I wondered what happens to the reference IDs when OpenStreetMap changes?
For example, In the case of:

1. A street is deleted and re-added with more accuracy. 
2. A street is updated such that it's initial 20 meters of bearing changes

And what happens if a street is not in OpenStreetMap? Particularly as we use the CLI tool.

This leads to my meta question. Perhaps you've answers this somewhere. Have you? And/or is there a better place to ask this question and/or save the results in case someone else has the question in the future?

Thanks!!

**Comment by emilyeros** [comment]
@kpwebb is the right person to answer this one. He's developed a process to compare changes between OSM data from different dates, such that changes can be [categorized](https://observablehq.com/@kpwebb/comparing-and-fast-forwarding-sharedstreets-references) and treated differently depending on how significant the OSM edit was. I'll let him explain more.

If a street is not in OpenStreetMap, It won't be in the SharedStreets reference tileset and will come back as unmatched. This will rarely happen in most urban areas since cities are generally well-mapped and those built environments aren't changing rapidly. If you do have unmatched streets because they don't exist in OSM, your best bet would be to verify that the streets are real, add them into OSM, and grab them in the next set of SharedStreets tiles. We know this isn't ideal for rapid turn-arounds; we've talked about having a forced update for smaller areas for these sorts of situations but haven't built anything for that yet.

You're welcome to ask questions here or in the [sharedstreets-js repo](https://github.com/sharedstreets/sharedstreets-js), which is more for the referencing system specifically.

**Comment by emilyeros** [comment]
No change needed, closing issue as part of github-gardening
