### ISSUE TITLE
Multiple regulations for given geometry

### ISSUE THREAD

**Issue by smohiudd** [sharedstreets/curblr#2]
If I have a number of different regulations for the same geometry (i.e. something like the ["Complex Regulations"](https://github.com/jfh01/CurbSpec/blob/master/examples/complex_examples.md) examples from CurbSpec) what's the best way to model that in the Restrictions? The spec doesn't specify the format for Restrictions but can we include an array of objects?

**Comment by emilyeros** [comment]
Great question. CurbLR holds one regulation (e.g. "No parking") per geometry. 

If you have multiple modifiers for that activity (e.g. Loading zone that applies on weekdays from 9-5, and also Sundays from 12-5) then you can just add those into the one feature. (There's an example of this at the bottom of the TimeClass.md page). 

But if you have two fundamentally different restrictions (e.g. Snow emergency Zone + resident parking only + No parking 2nd Tuesday due to street sweeping), then those need to be stored as three separate regulations. Each has its own Feature in the GeoJSON, even though the geometries will be identical.

We initially tried to do this as CurbSpec lays it out, where there is one geometry that can hold multiple regulations, but that was more unwieldy when converting sample city datasets into CurbLR. We've tried to be sensitive to varying cities' technical capacities, and thought it made sense to try to keep things simple for them. So we flattened the structure a bit for this first draft. Having a feature for each regulation also means offers some advantages/simplification for data visualization and mapping - overlapping regulations will each appear as their own object. They may need to be offset visually, but a city won't have to go through additional processing in order to visually display them. 

I'll put it on my list to add an example of this to GitHub next week. I held off on translating the complex examples for now; we anticipate (and hope for) lots of feedback in the next few weeks, and those examples take a lot of time to maintain. So I thought I'd do the hard examples once we have a v2 of CurbLR that cities and companies have had a chance to weigh in on.

Want to chat more about what you're doing with the rules engine? We're really interested in what you're doing in general (as well as any feedback on the draft spec)

**Comment by smohiudd** [comment]
Thanks for the response Emily. 

So even if you have a single geometry with different payment schedules during the same day you'll need a unique object (geometry + restriction) for each payment type?

I guess my comment is from a data consumption point of view. If for example you want all the rules for a specific curb geometry, will it be more efficient (for an API service for example) to create separate objects for each restriction or a deeper json format with nested restrictions? Or is that something for the developer to worry about and not necessarily the City/parking authority/CurbLR.

**Comment by smohiudd** [comment]
Have you also considered separating the geometries from the restrictions? Similar to GTFS where shapes, stop times, etc. are in different tables. 

Also, yes I'm available for a call - let's set something up!

**Comment by emilyeros** [comment]
^ that's a really good point about separating geometries from restrictions. We were hoping for a simple one-file format, but I think you're probably right and that's the direction we'll have to go.

I'll try to track down your email address or DM you about a meeting!

**Comment by emilyeros** [comment]
Addressed in new version - a given geometry can have multiple regulations.
